### PR TITLE
I changed the way we use long options.

### PR DESCRIPTION
**Pull request by FKuerten**
The old way, using indices in the option table, was very error prone, especially if options were added on different branches. Now we use integer constants > 255 to distinguish them.

This change might potentially break the windows getopt implementation, so please test it @MrHen

### CODE REVIEW

**Comment by MrHen** [comment]
I do not have access to my development machine over the holidays. I will have to test this after the new year.

**Comment by MrHen** [comment]
This does appear to break the Windows implementation. I am investigating.

**Comment by MrHen** [comment]
@Pr4370r14n: Okay, the problem comes down to how the implicit conversion from an int to char works. int 256 is converted into char 0 which means char(0) is the same as char(256). This seems like it would completely break how the enum + switch is working since the conversion happens when options[] is initialized. getopt stores the .val as a char.

I will put a hack in that will at least make the comparisons work but I am not convinced this is a completely proper solution.

**Comment by FKuerten** [comment]
Interesting. We probably should just change the char to int?

**Comment by FKuerten** [comment]
I don't like your fix. That might break stuff if we ever have a char in the same range.

getopt_long should return an int and the val field should take ints as well. In your windows implementation of getopt it is an wchar_t. Thats probably the bug?

I don't see where else this  could have broken for you.
Where is this "mplicit conversion from an int to char"?

**Comment by FKuerten** [comment]
I used a dirty work around, similar to yours. We might want to consider switching to something more portable, like boost options. But thats another thing.

**Comment by FKuerten** [comment]
(close was unintentional)

**Comment by MrHen** [comment]
getopt.h:91-98:

// Ansi
struct option_a
{
    const char\* name;
    int has_arg;
    int *flag;
    char val;
};

This is just above where you saw the wchar_t used for Unicode. Maybe I need to figure out how to switch my VS project to Unicode?

In any case, your new change worked just fine. I've opened issue #18 to track any future fix.

**Pull request merged**
