### PR TITLE
Raid tests

### LINKED ISSUE #4: Backfire bugs
leftlink posted a set of scenarios we are not handling appropriately.

http://www.kongregate.com/forums/65/topics/195043?page=73#posts-6619184

> Expected results for the following are all victories, but iteratedecks gives all draws:
>  ./iteratedecks P5 P0gA
>  ./iteratedecks PoI9 PoL3gA
>  ./iteratedecks Pog0 PogA
>  ./iteratedecks Pou7+j P0gA
>  ./iteratedecks P+K8+m RgAr+mgA 
> ./iteratedecks PoKh+i RggA
>  ./iteratedecks PoKF+j RggA -s
> 
> Expected result for the below test is victory, but iteratedecks gives loss:
>  ./iteratedecks RiL3 P0gAJj

### PR DESCRIPTION
**Pull request by MrHen**
This makes a few assumptions about how we want to scale testing. I zapped the individual Egg Infector test and included it in tests_summon and added the ability to verify draws.

Any thoughts about test organization?

Fixes #4 Backfire bugs

### CODE REVIEW

**Comment by FKuerten** [comment]
Not all tests pass. Is this intentional?
In particular the following fails:
emulate + on play
./iteratedecks-cli --verify 0:0 -o PoNifTMI QHNG

**Comment by MrHen** [comment]
No, this was not intentional. I thought I had checked all the tests... I will look into it.

**Comment by MrHen** [comment]
I just checked all of these tests again and they seem to work fine. Did you grab the latest xml files?

**Comment by FKuerten** [comment]
Yes. I use uptodate xml files. The branch is exactly as on github. This appears after my two commits, but also before.

**Comment by MrHen** [comment]
$ cat tests_emulate | test.sh ../../bin/ ../EvaluateDecks/DEBUG/CLI.exe
../EvaluateDecks/DEBUG/CLI.exe --verify 1:1 P9NG P7AG   fine
../EvaluateDecks/DEBUG/CLI.exe --verify 1:1 -o PoG6f2 P9NG      fine
../EvaluateDecks/DEBUG/CLI.exe --verify 1:1 PoNG SdBn   fine
../EvaluateDecks/DEBUG/CLI.exe --verify 1:1 RhNG QVHe   fine
../EvaluateDecks/DEBUG/CLI.exe --verify 0:0 -o PoG0u8 P9NG      fine
../EvaluateDecks/DEBUG/CLI.exe --verify 0:0 -o PoNifTMI QHNG    fine
Overall result: Good.

I am not seeing this failure. That is a little scary.

**Comment by MrHen** [comment]
Can you check the emulate test in your master? Something seems very wrong here; the tests are all passing just fine for me. I am not sure how to track down what went wrong if I cannot reproduce the issue.

**Comment by FKuerten** [comment]
Can no longer reproduice. All tests pass now. Must be something we merged from master.

**Pull request merged**
