### PR TITLE
Skill onkill

### PR DESCRIPTION
**Pull request by MrHen**

### CODE REVIEW

**Comment by FKuerten** [comment]
Does this already address the issue reported? (http://www.kongregate.com/forums/65-tyrant/topics/315978)

**Comment by MrHen** [comment]
Yes; rally on kill will ignore the triggering unit.

**Comment by MrHen** [comment]
@Pr4370r14n are you okay with this merge? Can we get it into master soon?

**Comment by FKuerten** [comment]
Sorry, I was quite busy. I'll have a look right now.

**Comment by FKuerten** [comment]
In general the master branch should always be merged into the feature branch. Then I can test the feature branch and if everything is fine I can be certain that the pull request will not break anything.
If master is not merged (but a recursive merge is possible) In rare circumstances the resulting merge might not be working.

So I just merged master into this and ran the checks.

**Comment by MrHen** [comment]
Thanks; no worries about timing. :)

Makes sense about the merging from master; way back when I opened the pull request I think it was up to date. ;)

**Pull request merged**
